# Generated by Django 4.0.1 on 2022-05-29 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PollApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='')),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
