# Generated by Django 4.0.1 on 2022-05-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0002_pollquestion_anonymous_pollquestion_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
