# Generated by Django 4.0.1 on 2022-05-30 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PollApp', '0003_alter_person_birthday_alter_person_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='voted',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
