# Generated by Django 4.0.1 on 2022-05-30 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PollApp', '0004_choice_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='voted',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='que_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
