# Generated by Django 4.0.1 on 2022-06-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0005_alter_choice_choice_image_alter_choice_choice_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
