# Generated by Django 4.0.1 on 2022-06-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0006_alter_person_birthday_alter_person_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='noofchoices',
            field=models.BigIntegerField(default=0),
        ),
    ]
