# Generated by Django 4.0.1 on 2022-06-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0007_pollquestion_noofchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='visiblity',
            field=models.BooleanField(default=True),
        ),
    ]
