# Generated by Django 4.0.1 on 2022-06-14 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PollApp', '0008_pollquestion_visiblity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PollApp.choice')),
                ('poll_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PollApp.pollquestion')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
