# Generated by Django 4.0.1 on 2022-06-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0009_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='poll_type',
            field=models.CharField(default='checkbox', max_length=122),
        ),
    ]
