# Generated by Django 4.0.1 on 2022-06-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0010_pollquestion_poll_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='poll_type',
            field=models.CharField(default='checkbox', max_length=122),
        ),
    ]
